---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - vendor/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/LineLength:
  Exclude:
    - test/**/*.rb
