---
language: ruby
script: bundle exec rake
sudo: false
cache: bundler
rvm:
  - 2.7.1
  - 2.6.5
gemfile:
  - gemfiles/6_0.gemfile
  - gemfiles/5_2.gemfile
notifications:
  email: false
before_install:
  - gem install bundler
before_script:
  - "curl -L
    https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter"
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: G5s7bzgQzX9fcD+Wj9pNq3ePjnFxOeu7Q39q3ZX6KfJctD0VIrKR+tHyXpr08GDjB4sbQjmEAyVVypmn2UeIGd5Uzi72euM4G5h09CssD/zgTROojihMj8EvKLRj2oBVk40zCyPNdl31TGMFI6auSxNzM4VI1f4f1BV6ejgAPt4=
